### ISSUE TITLE
Locked Variables

### ISSUE THREAD

**Issue by m-zaka** [Tecplot/handyscripts#2] opened 2019-04-25 08:56 UTC
After a bit of experimenting with the **tpmath.py**,  _compute_average_ function, i found that the script gives error if a variable is locked (e.g. by CFD ANALYZER).
is there a way to check if the variable is locked?
if the user does not know about this, such as me, it was much frustration because when the code reaches the following line, it gives error
`tp.data.operate.execute_equation("{%s} = 0"%(v.name), zones=[avg_zone])`
i think it could be avoided by using _constant_variables_?

**Comment by davetaflin** [comment] 2019-05-01 16:04
There is a way to check, but the Python interface might not be pretty (the C method is TecUtilVariableIsLocked). Would it help to know what causes variables to be locked? CFD Analyzer locks a variable against deletion (but not modification) if the variable is used as a source variable for other calculations--mainly if the variable is selected in the Field Variables dialog. A variable is locked against modification (but not deletion) if it is a CFD Analyzer calculate-on-demand variable--created with the Calculate dialog with the _Calculate on Demand_ toggle set. Is this sufficient information for you? If not, I'll ask Dr. Goetz to address querying for locked status using Python.

**Comment by theodoregoetz** [comment] 2019-05-01 17:34
After some investigation, I found that the TecUtilVariableIsLocked() method is not working from PyTecplot as intended. The affected versions are: PyTecplot 0.13 and Tecplot 360 2018 R2. We will fix this in the next release of Tecplot 360, but for now I'd suggest that a good solution is to wrap the `operate.execute_equation()` call with `try`/`except`. Also, you may contact support@tecplot.com if you are interested in trying out a beta of Tecplot 360 that includes a fix for this.

I'm closing this issue now because it has been added to our internal PyTecplot and Tecplot 360 issue boards.

**Closed as completed by theodoregoetz** 2019-05-01 17:34 UTC
Labels: bug, enhancement
